
package edu.lion.students;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseManagementImplService", targetNamespace = "http://students.lion.edu/", wsdlLocation = "http://localhost:7366/coursemanagement?wsdl")
public class CourseManagementImplService
    extends Service
{

    private final static URL COURSEMANAGEMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSEMANAGEMENTIMPLSERVICE_EXCEPTION;
    private final static QName COURSEMANAGEMENTIMPLSERVICE_QNAME = new QName("http://students.lion.edu/", "CourseManagementImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7366/coursemanagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSEMANAGEMENTIMPLSERVICE_WSDL_LOCATION = url;
        COURSEMANAGEMENTIMPLSERVICE_EXCEPTION = e;
    }

    public CourseManagementImplService() {
        super(__getWsdlLocation(), COURSEMANAGEMENTIMPLSERVICE_QNAME);
    }

    public CourseManagementImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSEMANAGEMENTIMPLSERVICE_QNAME, features);
    }

    public CourseManagementImplService(URL wsdlLocation) {
        super(wsdlLocation, COURSEMANAGEMENTIMPLSERVICE_QNAME);
    }

    public CourseManagementImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSEMANAGEMENTIMPLSERVICE_QNAME, features);
    }

    public CourseManagementImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseManagementImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseManagement
     */
    @WebEndpoint(name = "CourseManagementImplPort")
    public CourseManagement getCourseManagementImplPort() {
        return super.getPort(new QName("http://students.lion.edu/", "CourseManagementImplPort"), CourseManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseManagement
     */
    @WebEndpoint(name = "CourseManagementImplPort")
    public CourseManagement getCourseManagementImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://students.lion.edu/", "CourseManagementImplPort"), CourseManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSEMANAGEMENTIMPLSERVICE_EXCEPTION!= null) {
            throw COURSEMANAGEMENTIMPLSERVICE_EXCEPTION;
        }
        return COURSEMANAGEMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
